### ISSUE TITLE
Do not support android  platform，please support it

### ISSUE THREAD

**Issue by liweiww123** [emeraldpay/polkaj#21]
Can not use it in android applaction

**Comment by splix** [comment]
Hi @liweiww123. You're right, the lib doesn't have builds for Android. And I'm sure that some parts of the code are incompatible with Android. But can you please tell me more how you want to use the lib on Android, and what changed you need to make it working on Android?

**Comment by liweiww123** [comment]
@splix 
Thank you for your reply， because i want to add Polkadot function on my application , but the  polkadot official support  was bad.  Can't support native apps well.  so i find your team's project.  feels good.  but can not support android  platform.

if the polkaj  can similar to [web3j](https://github.com/web3j/web3j)  ,supports wallet create, private key import, transaction signature, and access to information on the chain, I think it has a great effect on the promotion of the Polkadot project.

**Comment by splix** [comment]
I have a very little experience with Android development, and would appreciate any suggestions, feature requests and bug reports. 

I currently provide the lib compiled with Java 11. To my understanding the latest versions of Android do support Java 11, can you confirm it?

If there is something that should be changed to make the lib working on Android, please create issues.

**Comment by liweiww123** [comment]
thanks
