### ISSUE TITLE
About pallet-contracts wrapper

### ISSUE THREAD

**Issue by AtenJin** [emeraldpay/polkaj#24]
Hi guys, we are https://github.com/patractlabs team, and we are focus on `pallet-contracts` part, trying to provide all develop tools for contracts developers.
Now we are planning to establish a project aim to compile wasm contracts and generate java code like what `web3j` do for Solidity. This java sdk would be an important part in our tools list, we would integrate different language sdk in to RedSpot(which like truffle in Ethereum) to be convenient for contracts developers.
So that this contracts java sdk depends on `polkaj` which provide codec system and rpc system.
Thus I come for ask whether we may have some cooperatation?
For example, our team just focus on `pallet-contracts` part, using `polkaj` as our previous dependent library, and we develop the part which need to use `ink!` to compile contracts and generate contracts java code, then use `polkaj` to connect to node. In this way, you guys do not need to waste time to develop the contracts part for `polkaj` which would cast a lot of time. you could just improve the core features for `polkaj`. On the other hand, we also could do some pr for `polkaj` to fix some bugs or other thing.

Or you guys just want to develop all parts by youself, include contracts part and other things?

Thank you very much!

**Comment by splix** [comment]
Hi @AtenJin. Thank you for reaching us out. It seems you're working on an interesting project, and we'll be happy to collaborate. 

While I wanted to have code generation module, there are a lot of other work to do and it would be great to have any help. It think the collaboration is the best approach. So you can focus on your side, and we can keep improving _polkaj_ as a base layer. Maybe you can contribute with missing parts or bugfixes as well, that would be awesome.

**Comment by AtenJin** [comment]
Happy to hear that, thank you very much!
What the ways of communication? Using Riot or email or something else? Or jus using github issue is enough?

**Comment by splix** [comment]
For things like issues Github would be the best, but for communication in general you can use my email splix@emerald.cash

**Comment by AtenJin** [comment]
> For things like issues Github would be the best, but for communication in general you can use my email [splix@emerald.cash](mailto:splix@emerald.cash)

get it, thank you very much!
