### ISSUE TITLE
Is it possible to use these  in maven project

### ISSUE THREAD

**Issue by BomaxChen** [emeraldpay/polkaj#26]
Hi ,  I try to use "gradle install" to build these jar to local maven repository, but in my maven project,  i add a maven dependency like:

 `<dependency> 
      <groupId>io.emeraldpay.polkaj</groupId>
      <artifactId>polkaj-api-http</artifactId>
      <version>0.4.0-SNAPSHOT</version>
 </dependency>`

--

then the error will occur at maven dependency and the message is "omitted for duplicate"

how do I solve this problem?  thanks a lot.

**Comment by BomaxChen** [comment]
>     <dependency>
      <groupId>io.emeraldpay.polkaj</groupId>
      <artifactId>polkaj-api-http</artifactId>
      <version>1.0.0</version>
    </dependency>

**Comment by BomaxChen** [comment]
[https://i.imgur.com/LcPJiOG.png](url)

**Comment by splix** [comment]
I guess `omitted for duplicate` only means that the IDE doesn't show it because it present in another place. Please try from command line, and see if it produce any error.
