### ISSUE TITLE
Is it possible to use polkaj to generate keypair by BIP39?

### ISSUE THREAD

**Issue by BomaxChen** [emeraldpay/polkaj#27]
as title, I only see use  Hex.decodeHex("hexseed") to generate keypair ,  is there any possible to generate keypair by mnemonic phrase ?  thanks a lot !

**Comment by splix** [comment]
I think you can use `MnemonicCode` class from `bitcoinj` lib to generate the input seed for the Polkaj KeyPair. 

I've checked the Javascript lib for Polkadot, it seems that it doesn't do anything special with BIP39. So I think it should be compatible but please check against keys generates from JS lib, if you want your keys be compatible with other apps.

**Comment by BomaxChen** [comment]
Thank you!  I'll try for that
