### ISSUE TITLE
Can not to transfer and balance of account is not right

### ISSUE THREAD

**Issue by EmilyCaoHong** [emeraldpay/polkaj#49]
![image](https://user-images.githubusercontent.com/43725403/110284181-5943fe80-801c-11eb-8242-89e56c22366b.png)
![image](https://user-images.githubusercontent.com/43725403/110284208-64972a00-801c-11eb-9e2c-ed5049f82368.png)
I use the example of the master project   https://github.com/emeraldpay/polkaj/blob/master/examples/balance/src/main/java/Transfer.java

**Comment by EmilyCaoHong** [comment]
@pablojorge @splix please help me. I am in a hurry.

**Comment by crow123** [comment]
this project is rubbish, give up! trying other

**Comment by EmilyCaoHong** [comment]
> 这个项目是垃圾，放弃！尝试其他

Do you have any other methods?

**Comment by EmilyCaoHong** [comment]
Do you have any other methods?&nbsp;&nbsp;

我能加你微信吗&nbsp; &nbsp;我需要做这个DOT开发 谢谢











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emeraldpay/polkaj"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 下午2:57
收件人:&nbsp;"emeraldpay/polkaj"<polkaj@noreply.github.com&gt;;
抄送:&nbsp;"〆彽灬凋"<171324551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [emeraldpay/polkaj] Can not to transfer and balance of account is not right (#49)





 
this project is rubbish, give up! trying other

**Comment by crow123** [comment]
Metadata metadata = client1.execute(StandardCommands.getInstance().stateMetadata())
                    .thenApply(ScaleExtract.fromBytesData(new MetadataReader()))
                    .get();

 ExtrinsicContext context = ExtrinsicContext.newAutoBuilder(alice, client)
                    .get()
                    .build();

你那边这两个方法执行正常？

**Comment by EmilyCaoHong** [comment]
第一个是正常的
Future<Metadata&gt; metadataFuture = client().execute(StandardCommands.getInstance().stateMetadata()) // (1)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .thenApply(ScaleExtract.fromBytesData(new MetadataReader())); // (2)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; System.out.println(metadataFuture.get());

第二个也是可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emeraldpay/polkaj"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 下午3:05
收件人:&nbsp;"emeraldpay/polkaj"<polkaj@noreply.github.com&gt;;
抄送:&nbsp;"〆彽灬凋"<171324551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [emeraldpay/polkaj] Can not to transfer and balance of account is not right (#49)





 
Metadata metadata = client1.execute(StandardCommands.getInstance().stateMetadata())
 .thenApply(ScaleExtract.fromBytesData(new MetadataReader()))
 .get();
 
ExtrinsicContext context = ExtrinsicContext.newAutoBuilder(alice, client)
 .get()
 .build();
 
你那边这两个方法执行正常？

**Comment by YuWT-CN** [comment]
这个工程在今年主链升级后已经无法使用了，影响的接口是转账失败，原因就是主链增加支持Multiaddress后，编码格式有变化，通过跟踪其他的钱包，主要变化需要在公钥编码器追加一个字节，普通地址为0x00，由于没有找到相关说明文档，逻辑未知。有懂js的可以翻翻源码。
<img width="842" alt="image" src="https://user-images.githubusercontent.com/73263860/110300062-691a0d80-8031-11eb-8a03-059f4cf77a11.png">

**Comment by EmilyCaoHong** [comment]
> 这个工程在今年主链升级后已经无法使用了，影响的接口是转账失败，原因就是主链增加支持Multiaddress后，编码格式有变化，通过跟踪其他的钱包，主要变化需要在公钥编码器追加一个字节，普通地址为0x00，由于没有找到相关说明文档，逻辑未知。有懂js的可以翻翻源码。
> <img alt="image" width="842" src="https://user-images.githubusercontent.com/73263860/110300062-691a0d80-8031-11eb-8a03-059f4cf77a11.png">

你改好了吗   能借鉴一下吗

**Comment by YuWT-CN** [comment]
io.emeraldpay.polkaj.scaletypes.ExtrinsicWriter.TransactionInfoWriter#write
<img width="820" alt="image" src="https://user-images.githubusercontent.com/73263860/110300878-6966d880-8032-11eb-91c3-5cfd2bb0e59a.png">
io.emeraldpay.polkaj.scaletypes.BalanceTransferWriter#write
<img width="819" alt="image" src="https://user-images.githubusercontent.com/73263860/110300921-7a174e80-8032-11eb-9e18-c18bbf046ad3.png">

修改这两处就可以解决当前的问题，由于是写死成0了，在一些其他情况可能需要传入别的值，没有找到相关文档，代码里目前还没看出来。

**Comment by EmilyCaoHong** [comment]
> io.emeraldpay.polkaj.scaletypes.ExtrinsicWriter.TransactionInfoWriter#write
> <img alt="image" width="820" src="https://user-images.githubusercontent.com/73263860/110300878-6966d880-8032-11eb-91c3-5cfd2bb0e59a.png">
> io.emeraldpay.polkaj.scaletypes.BalanceTransferWriter#write
> <img alt="image" width="819" src="https://user-images.githubusercontent.com/73263860/110300921-7a174e80-8032-11eb-9e18-c18bbf046ad3.png">
> 
> 修改这两处就可以解决当前的问题，由于是写死成0了，在一些其他情况可能需要传入别的值，没有找到相关文档，代码里目前还没看出来。

感谢~

**Comment by pablojorge** [comment]
These changes were introduced in Polkadot v0.8.28. I've been working on the fixes, I'll publish the PR soon

**Comment by EmilyCaoHong** [comment]
> These changes were introduced in Polkadot v0.8.28. I've been working on the fixes, I'll publish the PR soon

OK，Thanks

**Comment by EmilyCaoHong** [comment]
@pablojorge I use your branch  https://github.com/blockchain/polkaj，the balance is OK，but transfer is not OK，When will it be ready

**Comment by pablojorge** [comment]
> @pablojorge I use your branch [https://github.com/blockchain/polkaj，the](https://github.com/blockchain/polkaj%EF%BC%8Cthe) balance is OK，but transfer is not OK，When will it be ready

It's working fine on my tests, which specific error are you getting? Which version of polkadot are you using?

**Comment by EmilyCaoHong** [comment]
> > @pablojorge I use your branch [https://github.com/blockchain/polkaj，the](https://github.com/blockchain/polkaj%EF%BC%8Cthe) balance is OK，but transfer is not OK，When will it be ready
> 
> It's working fine on my tests, which specific error are you getting? Which version of polkadot are you using?

the balance is OK，but  the transfer is not OK without nothing tips. Can you give me the jar of all project?

**Comment by EmilyCaoHong** [comment]
> > @pablojorge I use your branch [https://github.com/blockchain/polkaj，the](https://github.com/blockchain/polkaj%EF%BC%8Cthe) balance is OK，but transfer is not OK，When will it be ready
> 
> It's working fine on my tests, which specific error are you getting? Which version of polkadot are you using?

I use polkadot 0.8.28-1-99043f78-x86_64-linux-gnu

**Comment by pablojorge** [comment]
Ok, I'm using the same version. I still don't know which error you get when you're trying to transfer. Regarding the .jar files, check the discussions in issues #31 and #46.

**Comment by EmilyCaoHong** [comment]
> Ok, I'm using the same version. I still don't know which error you get when you're trying to transfer. Regarding the .jar files, check the discussions in issues #31 and #46.
Thanks  I fixed the question, I use the jdk environment variable is 8，Changes to the 11， now  is ok  thank you very much
