### ISSUE TITLE
Repository to use the library

### ISSUE THREAD

**Issue by CrommVardek** [emeraldpay/polkaj#90]
Hello,

Bintray has been shutdown if I'm not mistaken. From now, is Polkaj accessible in a public maven repository ? The readme still shows this :

```
repositories {
   // polkaj public repo
   maven { url  "https://dl.bintray.com/emerald/polkaj" }
   // required for com.github.multiformats:java-multibase library
   maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'io.emeraldpay.polkaj:polkaj-api-http:0.3.0'
}
```

However when downloading the dependencies, it fails with the following error message : 

```
Could not resolve io.emeraldpay.polkaj:polkaj-api-http:0.3.0.
```

Thanks

**Comment by svalasovich** [comment]
Hi @CrommVardek 

Yes, it's old README and bintray service is not available [Into the Sunset on May 1st: Bintray, GoCenter, and ChartCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). I didn't find any other public repository for downloading polkaj dependency, but there are alternative download from github releases file directly if you need 0.3.0 version.

Example build.gradle.kts:
`
repositories {
    ivy("https://github.com") {
        patternLayout {
            artifact("[organisation]/releases/download/v[revision]/[module]-[revision].jar")
            setM2compatible(true)
        }
        metadataSources { artifact() }
    }
}

dependencies {
    implementation("emeraldpay.polkaj:polkaj-api-http:0.3.0")
}
`

**Comment by CrommVardek** [comment]
Sounds good, I'll try this out, thanks ! The goal was to avoid having a .jar dependency with the source code.
